# Generated by Django 2.2.4 on 2019-12-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Modell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('to 1990', ' To 1990'), ('from 1990 to 2000', 'From 1990 to 2000'), ('from 2000 to 2010', 'From 2000 to 2010'), ('after 2010', 'After 2010')], default='to 1990', max_length=10)),
                ('release', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_orders', to='auto.Marka')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_orders', to='auto.Modell')),
            ],
        ),
    ]
