# Generated by Django 2.2.4 on 2019-12-27 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marka',
            options={'ordering': ['marka']},
        ),
        migrations.AlterModelOptions(
            name='modell',
            options={'ordering': ['model']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['autor_name']},
        ),
        migrations.AlterModelManagers(
            name='marka',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modell',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='marka',
            name='marka',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='modell',
            name='model',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='autor_name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('to 1990', ' To 1990'), ('from 1990 to 2000', 'From 1990 to 2000'), ('from 2000 to 2010', 'From 2000 to 2010'), ('after 2010', 'After 2010')], default='to 1990', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markas', to='auto.Marka'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='auto.Modell'),
        ),
        migrations.AlterField(
            model_name='order',
            name='release',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('marka', 'model')},
        ),
    ]
